### ISSUE TITLE
Simple gRPC requests take much longer time for backend

### ISSUE THREAD

**Issue by pspgit** [Cysharp/YetAnotherHttpHandler#1]
Hello.
I've tried YetAnotherHttpHandler 0.1.0 with an example gRPC Greeter service.

When published to a remote server, it takes up to 200ms longer for backend to process each request sent with YetAnotherHttpHandler than with default .NET HttpHandler.
Can't find out, why a simple echo response takes so much time.

This does not reproduce when both client and server run on a local PC. 

An example Greeter service docker container I've used for test:
https://hub.docker.com/r/tobegit3hub/grpc-helloworld

Can be started with
docker run -d -p 50051:50051 tobegit3hub/grpc-helloworld

helloworld.proto for Client gRPC implementation:
https://github.com/grpc/grpc/blob/master/examples/protos/helloworld.proto

Client code (remove GrpcChannelOptions to try it with default HttpHandler) :

`   

    using var channel = GrpcChannel.ForAddress("http://server-ip:50051", new GrpcChannelOptions()
    {
        HttpHandler = new YetAnotherHttpHandler()
        {
            Http2Only = true,
            SkipCertificateVerification = true,
        }
    });
        
    var client = new Helloworld.Greeter.GreeterClient(channel);
    
    Stopwatch sw = new Stopwatch();
    for (int j = 0; j < 100; j++)
    {
        sw.Start();
        var reply = await client.SayHelloAsync(
            new HelloRequest { Name = "GreeterClient" });
        sw.Stop();
        
        Console.WriteLine("Greeting: " + reply.Message + " " + sw.ElapsedMilliseconds);
        sw.Reset();

        await Task.Delay(500);
    }  
`

The same reproduces with ASP .NET Core gRPC services and/or MagicOnion.

**Comment by kane9527-e** [comment]
Is this Docker project built by Unity ? 
Is this related to Unity's default. NET HttpHandler?

**Comment by pspgit** [comment]
Docker project is just an example server to demonstrate an issue.
Issue reproduces without Docker as well.

Default .NET HttpHandler is not available in Unity. I've used client .NET console app to demonstrate performance difference.

I've shared a repro console client here for convenience.
https://github.com/pspgit/YetAnotherHttpHandler-PerformanceIssueRepro/tree/PerformanceIssue-Repro
Branch: PerformanceIssue-Repro
Solution: repro/ConsoleApp1.sln

**Comment by mayuki** [comment]
It seems to reproduce when trying between environments with mid/high network latency. We will continue to investigate.

**Comment by mayuki** [comment]
I have tried to follow up and found that it is not always slow in my environment, but sometimes there are times when it slows down. This seems to be due to HTTP/2 window size adjustment, which includes latency for the communication of those packets.

## Japan (Home) -> Japan East (Azure)
```
YetAnotherHttpHandler
Yet Greeting: Hello, GreeterClient! 636
Yet Greeting: Hello, GreeterClient! 17
Yet Greeting: Hello, GreeterClient! 28  <-- WINDOW_UPDATE
Yet Greeting: Hello, GreeterClient! 14
Yet Greeting: Hello, GreeterClient! 15
Yet Greeting: Hello, GreeterClient! 34  <-- WINDOW_UPDATE
Yet Greeting: Hello, GreeterClient! 14
Yet Greeting: Hello, GreeterClient! 15
Yet Greeting: Hello, GreeterClient! 14
Yet Greeting: Hello, GreeterClient! 13

.NET HttpHandler
.NET Greeting: Hello, GreeterClient! 194
.NET Greeting: Hello, GreeterClient! 17
.NET Greeting: Hello, GreeterClient! 21
.NET Greeting: Hello, GreeterClient! 17
.NET Greeting: Hello, GreeterClient! 14
.NET Greeting: Hello, GreeterClient! 14
.NET Greeting: Hello, GreeterClient! 14
.NET Greeting: Hello, GreeterClient! 14
.NET Greeting: Hello, GreeterClient! 15
.NET Greeting: Hello, GreeterClient! 14
```

## Japan (Home) -> US West (Azure)

```
YetAnotherHttpHandler
Yet Greeting: Hello, GreeterClient! 1086
Yet Greeting: Hello, GreeterClient! 178
Yet Greeting: Hello, GreeterClient! 346  <-- WINDOW_UPDATE
Yet Greeting: Hello, GreeterClient! 178
Yet Greeting: Hello, GreeterClient! 173
Yet Greeting: Hello, GreeterClient! 173
Yet Greeting: Hello, GreeterClient! 172
Yet Greeting: Hello, GreeterClient! 173
Yet Greeting: Hello, GreeterClient! 173
Yet Greeting: Hello, GreeterClient! 344  <-- WINDOW_UPDATE

.NET HttpHandler
.NET Greeting: Hello, GreeterClient! 502
.NET Greeting: Hello, GreeterClient! 174
.NET Greeting: Hello, GreeterClient! 171
.NET Greeting: Hello, GreeterClient! 171
.NET Greeting: Hello, GreeterClient! 171
.NET Greeting: Hello, GreeterClient! 171
.NET Greeting: Hello, GreeterClient! 172
.NET Greeting: Hello, GreeterClient! 171
.NET Greeting: Hello, GreeterClient! 172
.NET Greeting: Hello, GreeterClient! 171
```

**Comment by pspgit** [comment]
For me, the slowdown is always stable (see example output in previous message).
I've tried it with 2 different hostings: GCore (dedicated server) and Digital Ocean (k8s). Both located in US-East.

What other things I could check?

I also see this with many clients using our Android app - often upstream duration take up to few seconds.
![image](https://github.com/Cysharp/YetAnotherHttpHandler/assets/2707493/57a07fa3-8cd2-4e14-8242-757a83ba5cf7)

**Comment by mayuki** [comment]
Can you tell me more about the environment in which you ran repro project? (OS, platform, etc.)

**Comment by pspgit** [comment]
I'm running console repro project on Windows 10:

Microsoft Windows 10 Home
Version	10.0.19045 Build 19045
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz, 1608 Mhz, 6 Core(s), 12 Logical Processor(s)
Total Physical Memory	31.8 GB
Internet Connection: Ethernet

The above graph is from Android app.

**Comment by pspgit** [comment]
I've tried to run repro project in a local docker container based on Ubuntu and the issue does not reproduce.
So it looks platform-dependent.

```
2023-08-08 11:47:42 YetAnotherHttpHandler
2023-08-08 11:47:42 Yet Greeting: Hello, GreeterClient! 437
2023-08-08 11:47:43 Yet Greeting: Hello, GreeterClient! 136
2023-08-08 11:47:43 Yet Greeting: Hello, GreeterClient! 136
2023-08-08 11:47:44 Yet Greeting: Hello, GreeterClient! 136
2023-08-08 11:47:44 Yet Greeting: Hello, GreeterClient! 135
2023-08-08 11:47:45 Yet Greeting: Hello, GreeterClient! 135
2023-08-08 11:47:45 Yet Greeting: Hello, GreeterClient! 136
2023-08-08 11:47:45 Yet Greeting: Hello, GreeterClient! 135
2023-08-08 11:47:46 Yet Greeting: Hello, GreeterClient! 135
2023-08-08 11:47:46 Yet Greeting: Hello, GreeterClient! 135
2023-08-08 11:47:47 
2023-08-08 11:47:47 .NET HttpHandler
2023-08-08 11:47:47 .NET Greeting: Hello, GreeterClient! 346
2023-08-08 11:47:47 .NET Greeting: Hello, GreeterClient! 137
2023-08-08 11:47:48 .NET Greeting: Hello, GreeterClient! 134
2023-08-08 11:47:48 .NET Greeting: Hello, GreeterClient! 133
2023-08-08 11:47:49 .NET Greeting: Hello, GreeterClient! 134
2023-08-08 11:47:49 .NET Greeting: Hello, GreeterClient! 134
2023-08-08 11:47:50 .NET Greeting: Hello, GreeterClient! 134
2023-08-08 11:47:50 .NET Greeting: Hello, GreeterClient! 134
2023-08-08 11:47:50 .NET Greeting: Hello, GreeterClient! 134
2023-08-08 11:47:51 .NET Greeting: Hello, GreeterClient! 138
```

**Comment by ahmet-voys** [comment]
Just to confirm @pspgit , we have the same issue from IOS clients. In the chart below you can see that latency increase occurred after we switched to YetAnotherHttpHandler. AFAIK, we use V1.0.1 

<img width="1889" alt="image" src="https://github.com/Cysharp/YetAnotherHttpHandler/assets/68007759/f98f36b2-6093-40b8-9d6f-4f6d054897dd">

**Comment by mayuki** [comment]
We have just released 1.2.1. 
We expect that disabling Nagle's Algorithm in this version will result in latency similar to C-core gRPC and SocketsHttpHandler.

The latency has improved as expected on my environments (.NET, Unity Editor and Android IL2CPP), but please let me know if you have any problems.

**Comment by Smirnov-Mikhail** [comment]
We tried 1.2.1 and we have same perfomance latency problem for our android users
I've simplified the graphic of our medium client-server request latency, but the key idea that we have worse connection for our real android users with YetAnotherHttpHandler and http2 than with UnityWebRequest and http1.1

Germany: less than 0.1 ---> more than 0.1
Japan and Korea: 0.15-0.35 ---> 0.15-0.95

it's data for thousands users in every country
![latency](https://github.com/Cysharp/YetAnotherHttpHandler/assets/6568161/3e38fc19-7702-4120-b270-2080d455cdf3)

**Comment by mayuki** [comment]
We always want to address performance issues, so let me check a few things.

- Is the problem Android-specific and not occurring e.g. on iOS or Windows?
- Is the connection with the server using YetAnotherHttpHandler HTTP/1 or HTTP/2?
    - YetAnotherHttpHandler can also communicate over HTTP/1.1
- Is the data being requested small data (like APIs) or large data (like assets)?

**Comment by Smirnov-Mikhail** [comment]
@mayuki 
1. We've tested only android devices, cannot provide info about another platfroms(
2. "After" section on my graphic uses YetAnotherHttpHandler and here is ~93% HTTP/2 and ~7% HTTP/1.1 (because we also have x32 devices)
3. Data is "small" (most of them less then 200 kilobytes), we've tested on our REST api (player data, configuration, statistic and etc)
