### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by slimshader** [Cysharp/YetAnotherHttpHandler#11]
hey, I see that WebGL is not supported yet but it also not mentioned under "not planned"

**Comment by Vinije** [comment]
Is it planned to support WebGL?

**Comment by mayuki** [comment]
As a prerequisite, WebGL operates on a web browser and cannot handle native Sockets, so it cannot communicate via HTTP/2.
There is no mechanism for directly controlling HTTP/2 communication from a web browser at the moment.

**Comment by Vinije** [comment]
Makes sense, thank you.
