### ISSUE TITLE
RequestTimeout option?

### ISSUE THREAD

**Issue by pspgit** [Cysharp/YetAnotherHttpHandler#114]
Hi
There is a ConnectTimeout property in YetAnotherHttpHandler, but I can't find a way to set RequestTimeout for any request. 
Is there a way to achieve this without directly setting Deadline for every request?

I use YetAnotherHttpHandler with MagicOnion. The idea is to have some global timeout for any gRPC request. 

`using var channel = GrpcChannel.ForAddress("https://api.example.com", new GrpcChannelOptions() { HttpHandler = new YetAnotherHttpHandler(), DisposeHttpClient = true });`

**Comment by mayuki** [comment]
You can specify a timeout using the `Timeout` property of `HttpClient`.

```csharp
var grpcOptions = new GrpcChannelOptions()
{
    HttpClient = new HttpClient(new YetAnotherHttpHandler() { Http2Only = true })
    {
        Timeout = TimeSpan.FromSeconds(10),
    },
    DisposeHttpClient = true,
};
```
