### ISSUE TITLE
Please document how to compile from source and add the results to a unity project

### ISSUE THREAD

**Issue by RubenGarcia** [Cysharp/YetAnotherHttpHandler#22]
```
cd native
cargo ndk -t arm64-v8a build
cd ..
dotnet pack YetAnotherHttpHandler.sln --runtime android-arm64 --include-symbols --include-source -o publish
```
generates
```
native/target/aarch64-linux-android/debug/libyaha_native.so
publish/YetAnotherHttpHandler.0.1.0.nupkg
publish/YetAnotherHttpHandler.0.1.0.symbols.nupkg
```
and publish/YetAnotherHttpHandler.0.1.0.nupkg contains Cysharp.Net.Http.YetAnotherHttpHandler.dll
but the installation from https://github.com/Cysharp/YetAnotherHttpHandler.git?path=src/YetAnotherHttpHandler#v0.1.0 provides instead
```
libCysharp.Net.Http.YetAnotherHttpHandler.Native.so
```
How is libCysharp.Net.Http.YetAnotherHttpHandler.Native.so created?

The build.yml instruction gives
```
unzip -o ./publish/YetAnotherHttpHandler.*[0-9].nupkg 'runtimes/*' -d src/YetAnotherHttpHandler/Plugins/Cysharp.Net.Http.YetAnotherHttpHandler.Native/ || true
Archive:  ./publish/YetAnotherHttpHandler.0.1.0.nupkg
caution: filename not matched:  runtimes/*
```

**Comment by RubenGarcia** [comment]
See https://github.com/Cysharp/YetAnotherHttpHandler/issues/18 for details on how to proceed.

**Comment by mayuki** [comment]
When creating a NuGet package, it is renamed from `libyaha_native.so` to `libCysharp.Net.Http.YetAnotherHttpHandler.so`, and the result of unzipping it is committed to Git. At this point, if you want to test it in a local environment, you need to manually rename and place it, or extract it from the NuGet package.

The path to the DLL referenced when creating a NuGet package is as follows:
```
native\artifacts\[target]\(lib)yaha_native.{so,dll}
```
https://github.com/Cysharp/YetAnotherHttpHandler/blob/1a7d5f0852b9059623f3ab11129d1bac44ad02c8/src/YetAnotherHttpHandler/YetAnotherHttpHandler.csproj#L79-L85
https://github.com/Cysharp/YetAnotherHttpHandler/blob/1a7d5f0852b9059623f3ab11129d1bac44ad02c8/src/YetAnotherHttpHandler/YetAnotherHttpHandler.csproj#L61-L63
