### ISSUE TITLE
Very important things about Unity2021.3.29f1 Carsh, IAsyncStreamReader<T>.MoveNext()

### ISSUE THREAD

**Issue by BoysheO** [Cysharp/YetAnotherHttpHandler#28]
When I call IAsyncStreamReader<T>.MoveNext(), Unity crashes every time. After I waste so much time, I found that call IAsyncStreamReader<T>.MoveNext() in the thread pool, all things are ok!

**Comment by jbne** [comment]
@BoysheO What errors were you getting and how did you call it in the thread pool? I am attempting to use ReadAllAsync and I get this error:

HttpRequestException: error trying to connect: tcp open error: The requested service provider could not be loaded or initialized. (os error 10106)

**Comment by BoysheO** [comment]
I dont think it is the same error what I talk.Are you sure that you have setup http handler correctly? @jbne

**Comment by jbne** [comment]
I managed to get this working a while ago by setting up the HTTP handler and the gRPC channel inside a MonoBehaviour Awake() function and doing the call handling inside a coroutine managed by the same MonoBehaviour.

**Comment by mayuki** [comment]
Is the platform where the error occurs iOS, Android or Windows? using IL2CPP for the build?

**Comment by BoysheO** [comment]
Today it crash again.No log,just a C++ Runtime Crash dialog.I still find the real crash reason. I think I must give up . = = wuwuwu

**Comment by BoysheO** [comment]
> Is the platform where the error occurs iOS, Android or Windows? using IL2CPP for the build?

My problem is in UnityEditor,Windows10

**Comment by mayuki** [comment]
This problem is probably fixed in v1.0.0 or later, so I close it. Please reopen if you continue to experience problems.
