### ISSUE TITLE
ARMv7 support on Android

### ISSUE THREAD

**Issue by bdovaz** [Cysharp/YetAnotherHttpHandler#4]
@mayuki I see that ARMv7 is not and will not be supported, only ARMv8 (ARM64).

https://github.com/Cysharp/YetAnotherHttpHandler#not-supported-not-planned

I'm curious why, because in our case we have a development that must be in JIT (Mono 32 bits) and not AOT (IL2CPP 64 bits) because we load assemblies dynamically and we can't use this library in Android.

I see that there is a workflow that is responsible for compiling each platform: https://github.com/Cysharp/YetAnotherHttpHandler/blob/main/.github/workflows/build.yml

Is it a question of not wanting to implement it? Is it difficult to implement?

Thanks!

**EDIT:** 

Under the hood I see it uses [hyper](https://hyper.rs/) and [Rustls](https://github.com/rustls/rustls): https://github.com/Cysharp/YetAnotherHttpHandler#under-the-hood

And at least rustls does work with ARMv7: https://github.com/rustls/rustls#platform-support

**Comment by mayuki** [comment]
In our normal use case, we did not have a 32-bit mono runtime on Android. We understand the need and would like to try to build a library for armv7.

**Comment by mayuki** [comment]
I have been able to build a native library for armv7.
I have not yet verified the library, but I believe it should work unless there is something special.
