### ISSUE TITLE
Win ARM64 support (.dll for HoloLens)

### ISSUE THREAD

**Issue by FlorianKehrle** [Cysharp/YetAnotherHttpHandler#43]
First of all - thanks for the great work on this project! 

I'm using MagicOnion for a project on HoloLens 2 and recently upgraded to the latest MagicOnion version as well as to YetAnotherHttpHandler as recommended. I managed to get it running in Unity, but when I deploy to the HoloLens, I get the following error, which is probably due to the missing Win ARM64 dll.
"DllNotFoundException: Unable to load DLL 'Cysharp.Net.Http.YetAnotherHttpHandler'"

I was wondering, if the win arm64 support is schedulled for the near future? Or if you know any workarounds for me?

**Comment by mangolas** [comment]
Here is experimental github actions snippet as well

```
  build-uwp-arm64:
    name: Build Native library (uwp-arm64)
    if: ${{ !inputs.build-only-linux }}
    runs-on: windows-2022
    timeout-minutes: 30
    defaults:
      run:
        working-directory: native
    steps:
      - uses: actions/checkout@v3
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - run: |
          rustup toolchain install nightly-x86_64-pc-windows-msvc
          rustup component add rust-src --toolchain nightly-x86_64-pc-windows-msvc
          rustup default nightly
          cargo update
          $env:Path += ";C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\bin"
          cargo -Z build-std build --target aarch64-uwp-windows-msvc
```

**Comment by FlorianKehrle** [comment]
Thanks for the quick respond and your workaround. I just tried it, unfortunately run into a problem at the last, build step and could't get it work so far:

```bash
  --- stdout
  cargo:rerun-if-env-changed=RING_PREGENERATE_ASM
  cargo:rustc-env=RING_CORE_PREFIX=ring_core_0_17_7_
  OPT_LEVEL = Some("0")
  TARGET = Some("aarch64-uwp-windows-msvc")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CC_aarch64-uwp-windows-msvc
  CC_aarch64-uwp-windows-msvc = None
  cargo:rerun-if-env-changed=CC_aarch64_uwp_windows_msvc
  CC_aarch64_uwp_windows_msvc = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("neon")
  DEBUG = Some("true")
  cargo:rerun-if-env-changed=CFLAGS_aarch64-uwp-windows-msvc
  CFLAGS_aarch64-uwp-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_uwp_windows_msvc
  CFLAGS_aarch64_uwp_windows_msvc = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None

 thread 'main' panicked at C:\Users\MYPATH\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ring-0.17.7\build.rs:673:9:
  failed to execute ["clang" "-O0" "--target=aarch64-uwp-windows-msvc" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "--target=aarch64-uwp-windows-msvc" "-I" "include" "-I" "MYPATH\\YetAnotherHttpHandler-main\\native\\target\\aarch64-uwp-windows-msvc\\debug\\build\\ring-1cde37458b6af70c\\out" "-Wall" "-Wextra" "-fvisibility=hidden" "-std=c1x" "-pedantic" "-Wall" "-Wextra" "-Wbad-function-cast" "-Wcast-align" "-Wcast-qual" "-Wconversion" "-Wenum-compare" "-Wfloat-equal" "-Wformat=2" "-Winline" "-Winvalid-pch" "-Wmissing-field-initializers" "-Wmissing-include-dirs" "-Wnested-externs" "-Wredundant-decls" "-Wshadow" "-Wsign-compare" "-Wsign-conversion" "-Wstrict-prototypes" "-Wundef" "-Wuninitialized" "-Wwrite-strings" "-g3" "-DNDEBUG" "-c" "-oC:\\MYPATH\\YetAnotherHttpHandler-main\\native\\target\\aarch64-uwp-windows-msvc\\debug\\build\\ring-1cde37458b6af70c\\out\\aesv8-armx-win64.o" "C:\\Users\\MYPATH\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\ring-0.17.7\\pregenerated\\aesv8-armx-win64.S"]: program not found
 ```

**Comment by mangolas** [comment]
That means `clang` executable is not in path. Which either means you did not add correct path to $env:Path or you have not installed Visual Studio CLang module. It's under C++ tools on Visual Studio Installer. Hope that helps!

**Comment by FlorianKehrle** [comment]
Yes, clang module under VS was missing, thanks so much. 

I had the same trouble you described including the dlls under Unity, but after setting the correct plattform settings for each dll (x64 -> Editor / arm64 -> WSA player), it seems to include the YetAnotherHttpHandler for HoloLens properly and the "DllNotFoundException" is gone (also had to reinstall YetAnotherHttpHandler to Unity via github). 

Unfortunatelly, I still have troubles with the grpc connection, but that seems to be another issue:
```
Grpc.Core.RpcException: Failed to connect to StreamingHub... Detail="Error starting gRPC call. NullReferenceException:
```
probably need to update my code for YetAnotherHttpHandler...

**Comment by FlorianKehrle** [comment]
It seems I overlooked an error last time and the HoloLens now finds the dll, but has trouble loading it. So when I Debug on the HoloLens I now get:

```
Grpc.Core.RpcException: Failed to connect to StreamingHub 'IMyHub'. 
(Status(StatusCode="Internal", Detail="Error starting gRPC call. DllNotFoundException: Unable to load DLL 'Cysharp.Net.Http.YetAnotherHttpHandler.Native'. Tried the load the following dynamic libraries: Unable to load dynamic library 'Cysharp.Net.Http.YetAnotherHttpHandler.Native' because of 'C:\build\output\unity\unity\External\il2cpp\builds\external\baselib\Source\WinApi\Baselib_DynamicLibrary_WinApi.inl.h(36):Baselib_DynamicLibrary_OpenUtf16: Failed to open the requested dynamic library (0x06000000) - The specified module could not be found.  
```

Did I miss copying some dependencies?

**Comment by mangolas** [comment]
I still suspect not the right dll is deployed. I would suggest you don't use Yaha from Github via manifest, but instead copy all files in your project, and then remove all other dll:s than the one you built to make it really sure that only one that is your dll is in built result. And make sure the filename is correct, dll name needs to be `Cysharp.Net.Http.YetAnotherHttpHandler.Native.dll`.

**Comment by FlorianKehrle** [comment]
Unfortunately, still not working - I went through, step by step, also rebuilt the the dll - but still the same error. 
```
....Baselib_DynamicLibrary_WinApi.inl.h(36):Baselib_DynamicLibrary_OpenUtf16: Failed to open the requested dynamic library (0x06000000) - The specified module could not be found.  (WinError:0000007e)
```
When I google that error, one suggestion is that dependencies are missing for the specific dll...maybe thats the case, however I installed all packages described in the yaha README

**Comment by FlorianKehrle** [comment]
Did the ```rustup update```, VisualStudio, Unity, etc. is up to date. When I build the ```x86_64-uwp-windows-msvc``` manually, include it in the project and debug in uity, I get the following error:
```
Grpc.Core.RpcException: Failed to connect to StreamingHub 'IMyHub'. (Status(StatusCode="Internal", Detail="Error starting gRPC call. DllNotFoundException: Cysharp.Net.Http.YetAnotherHttpHandler.Native assembly:<unknown assembly> type:<unknown type> member:(null)", DebugException="System.DllNotFoundException: Cysharp.Net.Http.YetAnotherHttpHandler.Native assembly:<unknown assembly> type:<unknown type> member:(null)")) ---> System.DllNotFoundException: Cysharp.Net.Http.YetAnotherHttpHandler.Native assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) Cysharp.Net.Http.NativeMethods.yaha_init_runtime()
```
When I use the prebuilt win-x64 library, everything works fine in unity. So I guess some dependencies in the build process are missing

**Comment by mangolas** [comment]
The dll from Rust target `x86_64-uwp-windows-msvc` does not work directly in Unity Editor mode, that is expected, only Rust target of `x86_64-pc-windows-msvc` will work there. What you can do with uwp dll, is build UWP Platform from Unity, and then compile the output targeting x86_64 in Visual Studio, the result is UWP application that you can run and debug directly in Windows. And make sure you have right CPU settings for dll's in place at Unity plugin preferences.

**Comment by FlorianKehrle** [comment]
Actually, for me it seems to be the same problem as [here](https://github.com/inthehand/32feet/issues/324). But I still have no clue how to solve it. I think (for now) I just wait until the ARM64 dll is included in the yaha project  or could you upload your working arm64 dll by any chance? 
Thanks anyway for the support

**Comment by mangolas** [comment]
<img width="429" alt="image" src="https://github.com/Cysharp/YetAnotherHttpHandler/assets/582250/2c777270-922b-4013-8ef0-4c3ab171c6c3">
<img width="395" alt="image" src="https://github.com/Cysharp/YetAnotherHttpHandler/assets/582250/549dc9cf-337d-4ff8-a37c-28f2c8f6c699">
<img width="399" alt="image" src="https://github.com/Cysharp/YetAnotherHttpHandler/assets/582250/1e14b521-32b2-49e3-b16a-ca5d7f04b68e">
<img width="238" alt="image" src="https://github.com/Cysharp/YetAnotherHttpHandler/assets/582250/3d97a429-ddcc-4240-b181-c4d819a541ac">
<img width="365" alt="image" src="https://github.com/Cysharp/YetAnotherHttpHandler/assets/582250/3c767e45-5faa-4b9e-88ce-69e69ceb25c1">
[YetAnotherHttpHandler-uwp-arm64.zip](https://github.com/Cysharp/YetAnotherHttpHandler/files/14259527/YetAnotherHttpHandler-uwp-arm64.zip)

Well, here it is then, and I added all other relevant settings I can think of, I really don't know why it does not work with you. And in my project I only have this single Yaha dll in it, to make sure that is what is being used.

**Comment by mangolas** [comment]
[YetAnotherHttpHandler-uwp-arm64.zip](https://github.com/Cysharp/YetAnotherHttpHandler/files/14259702/YetAnotherHttpHandler-uwp-arm64.zip)

**Comment by mangolas** [comment]
And make sure your managed libs are .Net Standard 2 or 2.1 versions...

**Comment by FlorianKehrle** [comment]
Still no luck...included all libs and settings from you - don't know what's left to try. 
I also tried to build the current MagicOnion ChatApp Sample again (with your settings and dll) and had the same error on the HoloLens while connecting to the local ChatApp server

**Comment by FlorianKehrle** [comment]
That cross compilation could be the problem, is also what I figuered with a colleague yesterday. Thanks a lot for the updated file and the idea, I cannot try it out today, but I will reach out as soon as I can test it.

**Comment by FlorianKehrle** [comment]
With your last arm64 version, yaha finally works on the HoloLens! It seems that crosscompilation was indeed the problem. 

My current procedure (if others want to run yaha in HoloLens until the official ARM64 release is ready): 
I removed yaha git addon in unity completely and just added the yaha source code (version 1.0.1) without the ```Plugins``` directory to my project. Added the [yaha_native_uwp_arm64.zip](https://github.com/Cysharp/YetAnotherHttpHandler/files/14293140/yaha_native_uwp_arm64.zip) from @mangolas and set to UWP / ARM64 in Unity. 

In my case, I also added the win-x64 plugin from the yaha source code, because I want to be able to start the app under unity as well. To be sure that the correct dll is used in each case, I changed in the ```NativeMethods.g.cs```:
```
namespace Cysharp.Net.Http
{
    internal static unsafe partial class NativeMethods
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#elif UNITY_EDITOR
        const string __DllName = "Cysharp.Net.Http.YetAnotherHttpHandler.Native";
#else
        const string __DllName = "yaha_native";
#endif
```

Thanks again for the support @mangolas!

**Comment by mangolas** [comment]
Great! Happy to hear you had success finally. I probably need to wrap all this up somehow as we need to have UWP capable Yaha eventually, but for now we'll manage with this manual setup. 

Looks like bumping Yaha's ring version from 0.16 needs rustls 0.22 but unfortunately that seems to break the compilation, and not quite sure how hard it is to fix, hopefully not too difficult.

**Comment by mangolas** [comment]
Added PR which does bump versions and compiles fine for UWP #49
