### ISSUE TITLE
Error:  Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.

### ISSUE THREAD

**Issue by TheNotary** [Cysharp/YetAnotherHttpHandler#70]
So whenever I press the play/ Stop button (invoking code I wrote to close the connection), it seems that the connection is not actually closed.  I know this by the error printed to the screen when I subsequently shutdown the grpc-server (implemented in C#).  Is this not enough to close the stream on the client's end?

```
public async void Disconnect()
{
    Debug.Log("Disconnect()");
    disconnected = true;
    if (channel != null)
    {
        await beCall.RequestStream.CompleteAsync();
        beCall.Dispose();

        await channel.ShutdownAsync();
        handler.Dispose();
        channel = null;
        client = null;
    }
}
```

Error: 
> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.

**Comment by mayuki** [comment]
Even if the Handler is disposed it will keep the ongoing request until completion, just like the SocketsHttpHandler.
If gRPC's DuplexStream is used, the connection may be kept until the server completes the response stream.

And `ChannelBase.ShutdownAsync` is a 'no-op' in grpc-dotnet and therefore it is recommended to use `GrpcChannel.Dispose`.

**Comment by TheNotary** [comment]
Ty for the note about `ChannelBase.ShutdownAsync`.  The `call.RequestStream.CompleteAsync()` approach seems to do the trick but I believe my reconnection logic has a flaw and is incorrectly re-opening the connection leading to the error I was seeing.
