### ISSUE TITLE
v1.3.0 gRPC requests won't go through

### ISSUE THREAD

**Issue by tetryds** [Cysharp/YetAnotherHttpHandler#73]
So I have gotten tired of 0.1.0 crashing Unity all the time and updated this library to the latest version 1.3.0. After doing so I have noticed that the gRPC requests stopped functioning. They would all get stuck awaiting for a response.

YAHH thinks a request has been sent when it really hasn't been received by the server. My gRPC backend hasn't received anything but YAHH got stuck awaiting for a response.

This has also led me to a few realizations:

* YAHH waits for a request indefinitely
* YAHH does not easily allow me to figure out what it is doing with logs and whatnot, or at least does not document how to do so
* The setup README.md is very confusing and mixes multiple installation strategies, which is annoying (I might sort it out myself)
* There was no documentation whatsoever for upgrading. I can only assume 1.x+ versions use the same dependencies but I had to reinstall it all just in case

My issue has been fixed reverting back to 1.2.0, and it is now working fine, but 1.3.0 is still not sending the requests no matter what I do.

**Comment by mayuki** [comment]
Sorry that the installation instructions are not easy and clear.

We have made some improvements to the lack of a way to get detailed logs, and you can now output a trace by specifying build constant `YAHA_ENABLE_DEBUG_TRACING` on Unity (https://github.com/Cysharp/YetAnotherHttpHandler/pull/80). Could you try this?

Please tell us more about your environment (server and client) if you don't mind, as we haven't encountered any issues with requests stopping in our environment/application so far.

**Comment by mayuki** [comment]
This issue may have been resolved in 1.4.2. If it still occurs, please feel free to reopen it.
