### ISSUE TITLE
Is there any way to get the Certificate data from the request?

### ISSUE THREAD

**Issue by sableangle** [Cysharp/YetAnotherHttpHandler#74]
If I would like to do a [Certificate Pinning](https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning) in the game, the Certificate raw data is required.

For instance, the UnityWebRequest provide an API [CertificateHandler](https://docs.unity3d.com/ScriptReference/Networking.CertificateHandler.html) which give us the cert raw datas, so we can do some extra verification for the certs.

If any api that provide similar features will be great!

**Comment by mayuki** [comment]
At present there is no such extension point, so you can only trust your own CA.
However, we understand that there is a need for certificate pinning in the game and would like to consider it.
