### ISSUE TITLE
Warning message is displayed due to omission of meta file deletion

### ISSUE THREAD

**Issue by housei** [Cysharp/YetAnotherHttpHandler#91]
Warning message is displayed due to omission of meta file deletion.

It would be appreciated if you could delete it as it is not necessary.

```
Couldn't delete Packages/com.cysharp.yetanotherhttphandler/NativeMethodsFuncPtr.g.cs.meta because it's in an immutable folder.
```

**Comment by mayuki** [comment]
Thanks. I forgot to delete the .meta file, so I deleted it and released v1.5.3.
