### ISSUE TITLE
Soft Restart for YetAnotherHttpHandler.cs

### ISSUE THREAD

**Issue by okankayhan** [Cysharp/YetAnotherHttpHandler#99]
I create your handler and pass it into several transports on game launch. During soft restarts, which I do for network errors, network mode switches(wifi, cellular) etc. , I would like to be able to kill all previous requests because they will eventually fail in an awkward state.

```
var serviceHost = $"https://{args.Host}:{args.Port}";
var channel = GrpcChannel.ForAddress(serviceHost, new GrpcChannelOptions
{
    HttpHandler = _httpHandler,
});

_grpcContext = new GrpcContext(channel, _cancellationTokenSource.Token);
_healthCheckServiceTransport = new HealthCheckServiceTransport(_grpcContext);
_authSrv = new AuthServiceTransport(_grpcContext);
```
Since I still want to reuse the `GrpcChannel`, it only makes sense to dispose and reinstantiate the handler. However current structure of `YetAnotherHttpHandler` does not allow that.

To fix this issue I had to clone the repo into my project and added this small tweak to `YetAnotherHttpHandler.cs`. It was impossible to solve this with extending due to `private` fields.
```
protected override void Dispose(bool disposing)
{
    _handler?.Dispose();
    _handler = null;
    // _disposed = true;
  >>_disposed = disposing;
}
```
Calling `Dispose(false)` during soft restarts works completely fine now, even though it feels a bit dirty.

I can open a MR for this or if you have a cleaner idea to like maybe adding a `void Restart` into handler it would be great. I would rather keep this repo as a package.

**Comment by okankayhan** [comment]
Pull Request https://github.com/Cysharp/YetAnotherHttpHandler/pull/100

**Comment by mayuki** [comment]
Thank you for the PR. However, the changes made by the PR are different from the originally intended behavior.
`YetAnotherHttpHandler` is not designed to be used after `Dispose`, and it would be unnatural for a .NET library to behave in this way.

For example, if you want to disconnect the gRPC currently being requested, it is preferable to `Dispose` and recreate the `GrpcChannel`. The `GrpcChannel` will cancel any requests that are in progress during `Dispose`.

In other words, it is not good to have the `YetAnotherHttpHandler` Disposed first, even though the `GrpcChannel` is being reused. (I think the same problem will occur with .NET's `SocketsHttpHandler`, etc.)

On the other hand, there is a way to reuse `YetAnotherHttpHandler` even if `GrpcChannel` is disposed. That is to [set `DisposeHttpClient` to `false` in `GrpcChannelOptions`](https://learn.microsoft.com/en-us/aspnet/core/grpc/configuration?view=aspnetcore-8.0#:~:text=to%20HttpHandler.-,DisposeHttpClient,-false).

**Comment by okankayhan** [comment]
Thank you for the response. As you suggested, I have decided to go for full dispose + reinitialize of channel and everything that had access to it.
